### ISSUE TITLE
The Date(Original) input cannot get values less than "02/06/2017"

### ISSUE THREAD

**Issue by prosperi** [LafayetteCollegeLibraries/metadb-ui#148]
![screen shot 2017-03-30 at 12 15 30 pm](https://cloud.githubusercontent.com/assets/13586782/24514521/94f06e1c-1542-11e7-9fea-8b0f80ea35ea.png)

**Comment by malantonio** [comment]
This is a side-effect of having the Slider component with the inputs. Since the Slider can't access a value lower/higher than the min/max values, we need to impose these limits on the `<input/>` elements (as the inputs are tied with the slider). 

I'm going to close this for the time being. Please let me know if this is something we should look to change.
